name = input("enter the name:")
print(name)
print(type(name))
college=input("enter the college name:")
print(college)
print(type(college))
branch_name=input("enter the branch name :")
print(branch_name)
print(type(branch_name))
rollno=input("enter the roll number:")
print(rollno)
print(type(rollno))
